name: Amazon Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y chromium-browser
          wget https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl

      - name: Run scraper
        run: |
          python scraper.py  # Replace with the name of your script
